name: Tim Ruby
favicon: null
layout_spectrum: 1
typography_spectrum: 0.53401
title: Designer/Front-end Developer
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#242223'
    - '#ddc4a8'
    - '#7db339'
    - '#85624f'
    - '#3976a1'
  brandStrength: 0.3125
  lightness: 0.4375
  saturation: 1
  rhythmicContrast: 0
purpose: []
