name: Tim Ruby
favicon: null
layout_spectrum: 1
typography_spectrum: 0.53401
title: Tim Ruby Grid.io Demo
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.6178383412770927
  lightness: 0.7688863931689411
  saturation: 0.8273771780077368
  rhythmicContrast: 0.6013032021000981
purpose: []
